// ============================================================
// CareerVerse AI — Assessment Questions Data
// ============================================================

import type { AssessmentQuestion } from './types';

export const assessmentQuestions: AssessmentQuestion[] = [
  // ── A. Where you're starting from ──
  {
    id: 'q1-stage',
    category: 'starting',
    categoryLabel: 'Where You Are Now',
    question: 'What stage of your career journey are you at?',
    subtitle: 'This helps us calibrate every suggestion to your reality.',
    type: 'single-select',
    options: [
      { value: 'school', label: 'School Student', description: 'Choosing a stream or thinking about college', emoji: '🎒' },
      { value: 'undergrad', label: 'Undergraduate', description: 'In college, picking a specialization or first job', emoji: '🎓' },
      { value: 'graduate', label: 'Recent Graduate', description: 'Completed degree, entering the job market', emoji: '📜' },
      { value: 'working', label: 'Working Professional', description: '1–10+ years of work experience', emoji: '💼' },
      { value: 'career-switcher', label: 'Career Switcher', description: 'Considering a move to a different field entirely', emoji: '🔄' },
    ],
    required: true,
    answerKey: 'currentStage',
  },
  {
    id: 'q2-field',
    category: 'starting',
    categoryLabel: 'Where You Are Now',
    question: "What's your current field of study or work?",
    subtitle: 'Type your stream, major, or job domain. Be specific — "Mechanical Engineering" is better than "Engineering."',
    type: 'free-text',
    placeholder: 'e.g., Computer Science, Commerce, Graphic Design, Marketing...',
    required: true,
    answerKey: 'fieldOfStudy',
  },
  {
    id: 'q3-skills',
    category: 'starting',
    categoryLabel: 'Where You Are Now',
    question: 'What are you genuinely good at?',
    subtitle: "Pick up to 5 skills or subjects where you perform above average. Be honest — this isn't a résumé.",
    type: 'multi-select',
    options: [
      { value: 'analytical-thinking', label: 'Analytical / Logical Thinking', emoji: '🧠' },
      { value: 'creative-design', label: 'Creative / Design', emoji: '🎨' },
      { value: 'writing-communication', label: 'Writing & Communication', emoji: '✍️' },
      { value: 'math-quantitative', label: 'Math & Quantitative Skills', emoji: '📊' },
      { value: 'coding-tech', label: 'Coding / Technology', emoji: '💻' },
      { value: 'people-skills', label: 'People Skills / Persuasion', emoji: '🤝' },
      { value: 'research', label: 'Research & Deep Diving', emoji: '🔍' },
      { value: 'leadership', label: 'Leadership & Organizing', emoji: '👑' },
      { value: 'hands-on', label: 'Hands-on / Building Things', emoji: '🔧' },
      { value: 'languages', label: 'Languages & Linguistics', emoji: '🌐' },
      { value: 'science', label: 'Science & Experimentation', emoji: '🔬' },
      { value: 'business-strategy', label: 'Business & Strategy', emoji: '📈' },
    ],
    required: true,
    answerKey: 'keySkills',
  },

  // ── B. What you actually want ──
  {
    id: 'q4-values',
    category: 'desires',
    categoryLabel: 'What Matters to You',
    question: 'Rank these by how much they matter to you right now.',
    subtitle: "Drag to reorder — #1 is what you'd optimize for above all else. There are no wrong answers.",
    type: 'ranking',
    options: [
      { value: 'money', label: 'Money & Wealth', description: 'Earning power, high salary, financial freedom', emoji: '💰' },
      { value: 'stability', label: 'Stability & Security', description: 'Predictable income, job safety, low anxiety', emoji: '🛡️' },
      { value: 'passion', label: 'Passion & Enjoyment', description: 'Doing work you genuinely love every day', emoji: '❤️' },
      { value: 'impact', label: 'Impact & Purpose', description: 'Making a difference, contributing to something meaningful', emoji: '🌍' },
      { value: 'fame', label: 'Fame & Recognition', description: 'Being known, respected, building a personal brand', emoji: '⭐' },
      { value: 'freedom', label: 'Freedom & Flexibility', description: 'Control over your time, location, and decisions', emoji: '🕊️' },
    ],
    required: true,
    answerKey: 'valuePriorities',
  },
  {
    id: 'q5-workstyle',
    category: 'desires',
    categoryLabel: 'What Matters to You',
    question: 'How do you do your best work?',
    subtitle: "Think about when you've felt most productive and engaged.",
    type: 'single-select',
    options: [
      { value: 'solo', label: 'Deep Solo Work', description: "Give me a quiet space and a hard problem — I'll figure it out", emoji: '🎯' },
      { value: 'team', label: 'Team Collaboration', description: 'I thrive when brainstorming, discussing, and building with others', emoji: '👥' },
      { value: 'leadership', label: 'Leading & Managing', description: "I'm at my best when I'm organizing people and driving outcomes", emoji: '🚀' },
    ],
    required: true,
    answerKey: 'workStyle',
  },
  {
    id: 'q6-environment',
    category: 'desires',
    categoryLabel: 'What Matters to You',
    question: 'Where do you see yourself working?',
    type: 'single-select',
    options: [
      { value: 'office', label: 'Office / Corporate', description: 'Structured environment, colleagues around, clear hierarchy', emoji: '🏢' },
      { value: 'remote', label: 'Remote / Work from Anywhere', description: 'Laptop lifestyle, async communication, location freedom', emoji: '🏠' },
      { value: 'field', label: 'Field Work / On-site', description: 'Out in the world — labs, sites, travel, client meetings', emoji: '🌿' },
      { value: 'hybrid', label: 'Hybrid / Flexible', description: 'Mix of office and remote — best of both worlds', emoji: '🔀' },
      { value: 'entrepreneurial', label: 'Own Business / Startup', description: 'Building something of my own, wearing all hats', emoji: '🏗️' },
    ],
    required: true,
    answerKey: 'environment',
  },

  // ── C. Risk & constraints ──
  {
    id: 'q7-risk',
    category: 'constraints',
    categoryLabel: 'Your Reality Check',
    question: 'How much risk can you stomach?',
    subtitle: "Be honest — there's no brave or cowardly answer, only realistic ones.",
    type: 'single-select',
    options: [
      { value: 'stable', label: 'Stable Paycheck, Please', description: "I need predictability. Bills don't wait for \"someday.\"", emoji: '🏦' },
      { value: 'moderate', label: 'Calculated Risks', description: 'I can handle some uncertainty if the upside is clear.', emoji: '⚖️' },
      { value: 'high-risk', label: 'High Risk, High Reward', description: "I'm willing to bet years on a big payoff — even if it might not work.", emoji: '🎲' },
    ],
    required: true,
    answerKey: 'riskTolerance',
  },
  {
    id: 'q8-financial',
    category: 'constraints',
    categoryLabel: 'Your Reality Check',
    question: 'What does your financial situation look like?',
    subtitle: 'This shapes how quickly you need a career to start paying off.',
    type: 'single-select',
    options: [
      { value: 'no-pressure', label: 'No Immediate Pressure', description: 'Family support or savings — I can invest time in building skills', emoji: '😌' },
      { value: 'moderate-pressure', label: 'Some Responsibility', description: 'Need income within a year but not immediately desperate', emoji: '⏳' },
      { value: 'high-pressure', label: 'Need Income Soon', description: 'Supporting family or self — need a paying role quickly', emoji: '⚡' },
    ],
    required: true,
    answerKey: 'financialSituation',
  },
  {
    id: 'q9-location',
    category: 'constraints',
    categoryLabel: 'Your Reality Check',
    question: 'How flexible are you about where you live?',
    type: 'single-select',
    options: [
      { value: 'anywhere', label: 'Anywhere in India or Abroad', description: "I'll go where the best opportunity is", emoji: '✈️' },
      { value: 'metro-cities', label: 'Major Indian Cities', description: 'Bangalore, Mumbai, Delhi NCR, Hyderabad, Pune, Chennai', emoji: '🏙️' },
      { value: 'home-state', label: 'My Home State / Region', description: 'I prefer staying close to home and family', emoji: '🏡' },
      { value: 'rooted', label: "Can't Relocate", description: 'I need to stay exactly where I am', emoji: '📍' },
    ],
    required: true,
    answerKey: 'locationFlexibility',
  },
  {
    id: 'q10-timeline',
    category: 'constraints',
    categoryLabel: 'Your Reality Check',
    question: 'How many years are you willing to invest before a big payoff?',
    subtitle: 'Think about further study, building a startup, or climbing a slow but high-ceiling ladder.',
    type: 'slider',
    min: 1,
    max: 10,
    minLabel: '1 year — I need results fast',
    maxLabel: "10 years — I'm playing the long game",
    required: true,
    answerKey: 'timeHorizon',
  },

  // ── D. The emotional / human side ──
  {
    id: 'q11-energy',
    category: 'emotional',
    categoryLabel: 'The Human Side',
    question: 'What energizes you vs. what drains you?',
    subtitle: 'Describe in a sentence or two. For example: "I love solving puzzles but hate repetitive data entry" or "I enjoy talking to people but meetings exhaust me."',
    type: 'free-text',
    placeholder: 'I feel energized when... and drained when...',
    required: true,
    answerKey: 'energizesVsDrains',
  },
  {
    id: 'q12-worstcase',
    category: 'emotional',
    categoryLabel: 'The Human Side',
    question: 'The hardest trade-off: which life would you rather live?',
    subtitle: 'This single question often reveals more than all the others combined. Trust your gut.',
    type: 'scenario',
    options: [
      {
        value: 'boring-stable',
        label: 'The Stable Road',
        description: "A predictable, well-paying job that's a bit boring. You'll never love Monday mornings, but you'll sleep well every night. Your family is comfortable, and you have time for hobbies.",
        emoji: '🛋️',
      },
      {
        value: 'exciting-unstable',
        label: 'The Wild Ride',
        description: 'An exciting, meaningful career with real highs — but also real lows. Some months are incredible, others are terrifying. You might build something amazing or learn a painful lesson.',
        emoji: '🎢',
      },
    ],
    required: true,
    answerKey: 'worstCaseTolerance',
  },
];
